[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  

[[redirects]]
  from = "/object/:object"
  to = "/object/[tokenId].html?object=:tokenId"
  status = 200

[[redirects]]
  from = "/created/:created"
  to = "/created/[account].html?object=:account"
  status = 200

[[redirects]]
  from = "/owned/:owned"
  to = "/owned/[account].html?object=:account"
  status = 200

[[redirects]]
  from = "/bids/:bids"
  to = "/bids/[account].html?object=:account"
  status = 200

[[redirects]]
  from = "/user/:user"
  to = "/user/[user].html?object=:user"
  status = 200

[[redirects]]
  from = "/forSale/:forSale"
  to = "/forSale/[account].html?object=:account"
  status = 200

[[redirects]]
  from = "/mint/:mint"
  to = "/mint/:mint"
  status = 200

[[redirects]]
  from = "/mints/:mints"
  to = "/mints/:mints"
  status = 200

[[redirects]]
  from = "/editAccount/:editAccount"
  to = "/editAccount/:editAccount"
  status = 200

[[redirects]]
  from = "/whitelist/:whitelist"
  to = "/whitelist/:whitelist"
  status = 200

[[redirects]]
  from = "/search/:search"
  to = "/search/:search"
  status = 200

[[redirects]]
  from = "/gallery/:gallery"
  to = "/gallery/:gallery"
  status = 200

[[redirects]]
  from = "/leaderboard/:leaderboard"
  to = "/leaderboard/:leaderboard"
  status = 200

[[redirects]]
  from = "/admin/:admin"
  to = "/admin/:admin"
  status = 200


# you can also target a specific branch
[context.v0.environment]
  V0_ADDRESS = "address"
  BRANCH = "v0" # TEST: should be deploy or something other than production